// Generator : SpinalHDL v1.9.0    git head : 7d30dbacbd3aa1be42fb2a3d4da5675703aae2ae
// Component : fp_mac
// Git hash  : c982d0aac03e1ed897d6c33309713a5773bade24

`timescale 1ns/1ps 
module fp_mac (
  input      [31:0]   io_a,
  input      [31:0]   io_b,
  input      [31:0]   io_c,
  input      [2:0]    io_rnd,
  output reg [31:0]   io_z,
  output reg [7:0]    io_status,
  input               clk,
  input               resetn
);

  wire       [23:0]   man_booth4_io_a;
  wire       [23:0]   man_booth4_io_b;
  wire       [47:0]   man_booth4_io_z;
  wire       [0:0]    tmp_a_hidden;
  wire       [0:0]    tmp_b_hidden;
  wire       [0:0]    tmp_c_hidden;
  wire       [7:0]    tmp_product_exp;
  wire       [95:0]   tmp_c_man_ext;
  wire       [71:0]   tmp_c_man_ext_1;
  wire       [95:0]   tmp_product_man;
  wire       [71:0]   tmp_product_man_1;
  wire       [47:0]   tmp_product_man_2;
  wire       [71:0]   tmp_c_man_shift;
  wire       [71:0]   tmp_product_shift;
  wire       [94:0]   tmp_c_man_align;
  wire       [72:0]   tmp_prod_mag_s;
  wire       [72:0]   tmp_c_mag_s;
  wire       [72:0]   tmp_prod_val;
  wire       [72:0]   tmp_c_val;
  wire       [73:0]   tmp_sum_man;
  wire       [73:0]   tmp_sum_man_1;
  wire       [73:0]   tmp_sum_man_abs_all;
  wire       [73:0]   tmp_sum_man_abs_all_1;
  wire       [73:0]   tmp_sum_man_abs_all_2;
  wire       [0:0]    tmp_sum_man_abs_all_3;
  wire       [73:0]   tmp_sum_man_sign_r3;
  wire       [73:0]   tmp_sum_man_sign_r3_1;
  wire       [71:0]   tmp_sum_man_vec_0;
  wire       [71:0]   tmp_sum_man_vec_1;
  wire       [71:0]   tmp_sum_man_vec_2;
  wire       [71:0]   tmp_sum_man_vec_3;
  wire       [71:0]   tmp_sum_man_vec_4;
  wire       [71:0]   tmp_sum_man_vec_5;
  wire       [71:0]   tmp_sum_man_vec_6;
  wire       [71:0]   tmp_sum_man_vec_7;
  wire       [71:0]   tmp_sum_man_vec_8;
  wire       [71:0]   tmp_sum_man_vec_9;
  wire       [71:0]   tmp_sum_man_vec_10;
  wire       [71:0]   tmp_sum_man_vec_11;
  wire       [71:0]   tmp_sum_man_vec_12;
  wire       [71:0]   tmp_sum_man_vec_13;
  wire       [71:0]   tmp_sum_man_vec_14;
  wire       [71:0]   tmp_sum_man_vec_15;
  wire       [71:0]   tmp_sum_man_vec_16;
  wire       [71:0]   tmp_sum_man_vec_17;
  wire       [71:0]   tmp_sum_man_vec_18;
  wire       [71:0]   tmp_sum_man_vec_19;
  wire       [71:0]   tmp_sum_man_vec_20;
  wire       [71:0]   tmp_sum_man_vec_21;
  wire       [71:0]   tmp_sum_man_vec_22;
  wire       [71:0]   tmp_sum_man_vec_23;
  wire       [71:0]   tmp_sum_man_vec_24;
  wire       [71:0]   tmp_sum_man_vec_25;
  wire       [71:0]   tmp_sum_man_vec_26;
  wire       [71:0]   tmp_sum_man_vec_27;
  wire       [71:0]   tmp_sum_man_vec_28;
  wire       [71:0]   tmp_sum_man_vec_29;
  wire       [71:0]   tmp_sum_man_vec_30;
  wire       [71:0]   tmp_sum_man_vec_31;
  wire       [71:0]   tmp_sum_man_vec_32;
  wire       [71:0]   tmp_sum_man_vec_33;
  wire       [71:0]   tmp_sum_man_vec_34;
  wire       [71:0]   tmp_sum_man_vec_35;
  wire       [71:0]   tmp_sum_man_vec_36;
  wire       [71:0]   tmp_sum_man_vec_37;
  wire       [71:0]   tmp_sum_man_vec_38;
  wire       [71:0]   tmp_sum_man_vec_39;
  wire       [71:0]   tmp_sum_man_vec_40;
  wire       [71:0]   tmp_sum_man_vec_41;
  wire       [71:0]   tmp_sum_man_vec_42;
  wire       [71:0]   tmp_sum_man_vec_43;
  wire       [71:0]   tmp_sum_man_vec_44;
  wire       [71:0]   tmp_sum_man_vec_45;
  wire       [71:0]   tmp_sum_man_vec_46;
  wire       [71:0]   tmp_sum_man_vec_47;
  wire       [71:0]   tmp_sum_man_vec_48;
  wire       [71:0]   tmp_sum_man_vec_49;
  wire       [71:0]   tmp_sum_man_vec_50;
  wire       [71:0]   tmp_sum_man_vec_51;
  wire       [71:0]   tmp_sum_man_vec_52;
  wire       [71:0]   tmp_sum_man_vec_53;
  wire       [71:0]   tmp_sum_man_vec_54;
  wire       [71:0]   tmp_sum_man_vec_55;
  wire       [71:0]   tmp_sum_man_vec_56;
  wire       [71:0]   tmp_sum_man_vec_57;
  wire       [71:0]   tmp_sum_man_vec_58;
  wire       [71:0]   tmp_sum_man_vec_59;
  wire       [71:0]   tmp_sum_man_vec_60;
  wire       [71:0]   tmp_sum_man_vec_61;
  wire       [71:0]   tmp_sum_man_vec_62;
  wire       [71:0]   tmp_sum_man_vec_63;
  wire       [71:0]   tmp_sum_man_vec_64;
  wire       [71:0]   tmp_sum_man_vec_65;
  wire       [71:0]   tmp_sum_man_vec_66;
  wire       [71:0]   tmp_sum_man_vec_67;
  wire       [71:0]   tmp_sum_man_vec_68;
  wire       [71:0]   tmp_sum_man_vec_69;
  wire       [71:0]   tmp_sum_man_vec_70;
  wire       [71:0]   tmp_sum_man_vec_71;
  wire                tmp_found_71;
  wire                tmp_found_72;
  wire                tmp_found_73;
  wire                tmp_found_74;
  wire       [6:0]    tmp_lzc;
  wire       [6:0]    tmp_lzc_1;
  wire       [6:0]    tmp_lzc_2;
  wire       [6:0]    tmp_lzc_3;
  wire       [6:0]    tmp_lzc_4;
  wire       [6:0]    tmp_lzc_5;
  wire       [6:0]    tmp_lzc_6;
  wire       [6:0]    tmp_lzc_7;
  wire       [6:0]    tmp_lzc_8;
  wire       [6:0]    tmp_lzc_9;
  wire       [6:0]    tmp_lzc_10;
  wire       [6:0]    tmp_lzc_11;
  wire       [6:0]    tmp_lzc_real;
  wire       [71:0]   tmp_norm_man;
  wire       [71:0]   tmp_norm_man_1;
  wire       [71:0]   tmp_norm_man_2;
  wire       [198:0]  tmp_norm_man_3;
  wire       [7:0]    tmp_result_exp;
  wire       [7:0]    tmp_result_exp_1;
  wire       [7:0]    tmp_result_exp_2;
  wire       [7:0]    tmp_result_exp_3;
  wire       [0:0]    tmp_result_exp_4;
  wire       [7:0]    tmp_result_exp_5;
  wire       [0:0]    tmp_result_exp_6;
  wire       [0:0]    tmp_round_up_1;
  wire       [22:0]   tmp_man_rounded;
  wire       [0:0]    tmp_man_rounded_1;
  wire       [7:0]    tmp_exp_final;
  wire       [0:0]    tmp_exp_final_1;
  wire       [31:0]   tmp_norm_num;
  wire       [31:0]   tmp_subnorm_num;
  wire       [31:0]   tmp_subnorm_num_1;
  wire                a_sign;
  wire                b_sign;
  wire                c_sign;
  wire       [7:0]    a_exp;
  wire       [7:0]    b_exp;
  wire       [7:0]    c_exp;
  wire       [22:0]   a_man;
  wire       [22:0]   b_man;
  wire       [22:0]   c_man;
  wire       [0:0]    a_hidden;
  wire       [0:0]    b_hidden;
  wire       [0:0]    c_hidden;
  wire       [23:0]   a_man_1;
  wire       [23:0]   b_man_1;
  wire       [23:0]   c_man_1;
  wire                product_sign;
  wire       [7:0]    exp_all_one;
  wire                a_is_inf;
  wire                b_is_inf;
  wire                c_is_inf;
  wire                a_is_nan;
  wire                b_is_nan;
  wire                c_is_nan;
  wire                output_nan;
  wire                a_b_inf;
  wire                a_zero;
  wire                b_zero;
  wire                inf_x_zero;
  wire                prod_is_inf;
