// Generator : SpinalHDL v1.9.0    git head : 7d30dbacbd3aa1be42fb2a3d4da5675703aae2ae
// Component : fp_mac
// Git hash  : c982d0aac03e1ed897d6c33309713a5773bade24

`timescale 1ns/1ps 
module fp_mac (
  input      [31:0]   io_a,
  input      [31:0]   io_b,
  input      [31:0]   io_c,
  input      [2:0]    io_rnd,
  output reg [31:0]   io_z,
  output reg [7:0]    io_status,
  input               clk,
  input               resetn
);

  wire       [23:0]   man_booth4_io_a;
  wire       [23:0]   man_booth4_io_b;
  wire       [47:0]   man_booth4_io_z;
  wire       [0:0]    tmp_a_hidden;
  wire       [0:0]    tmp_b_hidden;
  wire       [0:0]    tmp_c_hidden;
  wire       [7:0]    tmp_product_exp;
  wire       [95:0]   tmp_c_man_ext;
  wire       [71:0]   tmp_c_man_ext_1;
  wire       [95:0]   tmp_product_man;
  wire       [71:0]   tmp_product_man_1;
  wire       [47:0]   tmp_product_man_2;
  wire       [71:0]   tmp_c_man_shift;
  wire       [71:0]   tmp_product_shift;
  wire       [94:0]   tmp_c_man_align;
  wire       [72:0]   tmp_prod_mag_s;
  wire       [72:0]   tmp_c_mag_s;
  wire       [72:0]   tmp_prod_val;
  wire       [72:0]   tmp_c_val;
  wire       [73:0]   tmp_sum_man;
  wire       [73:0]   tmp_sum_man_1;
  wire       [73:0]   tmp_sum_man_abs_all;
  wire       [73:0]   tmp_sum_man_abs_all_1;
  wire       [73:0]   tmp_sum_man_abs_all_2;
  wire       [0:0]    tmp_sum_man_abs_all_3;
  wire       [73:0]   tmp_sum_man_sign_r3;
  wire       [73:0]   tmp_sum_man_sign_r3_1;
  wire       [71:0]   tmp_sum_man_vec_0;
  wire       [71:0]   tmp_sum_man_vec_1;
  wire       [71:0]   tmp_sum_man_vec_2;
  wire       [71:0]   tmp_sum_man_vec_3;
  wire       [71:0]   tmp_sum_man_vec_4;
  wire       [71:0]   tmp_sum_man_vec_5;
  wire       [71:0]   tmp_sum_man_vec_6;
  wire       [71:0]   tmp_sum_man_vec_7;
  wire       [71:0]   tmp_sum_man_vec_8;
  wire       [71:0]   tmp_sum_man_vec_9;
  wire       [71:0]   tmp_sum_man_vec_10;
  wire       [71:0]   tmp_sum_man_vec_11;
  wire       [71:0]   tmp_sum_man_vec_12;
  wire       [71:0]   tmp_sum_man_vec_13;
  wire       [71:0]   tmp_sum_man_vec_14;
  wire       [71:0]   tmp_sum_man_vec_15;
  wire       [71:0]   tmp_sum_man_vec_16;
  wire       [71:0]   tmp_sum_man_vec_17;
  wire       [71:0]   tmp_sum_man_vec_18;
  wire       [71:0]   tmp_sum_man_vec_19;
  wire       [71:0]   tmp_sum_man_vec_20;
  wire       [71:0]   tmp_sum_man_vec_21;
  wire       [71:0]   tmp_sum_man_vec_22;
  wire       [71:0]   tmp_sum_man_vec_23;
  wire       [71:0]   tmp_sum_man_vec_24;
  wire       [71:0]   tmp_sum_man_vec_25;
  wire       [71:0]   tmp_sum_man_vec_26;
  wire       [71:0]   tmp_sum_man_vec_27;
  wire       [71:0]   tmp_sum_man_vec_28;
  wire       [71:0]   tmp_sum_man_vec_29;
  wire       [71:0]   tmp_sum_man_vec_30;
  wire       [71:0]   tmp_sum_man_vec_31;
  wire       [71:0]   tmp_sum_man_vec_32;
  wire       [71:0]   tmp_sum_man_vec_33;
  wire       [71:0]   tmp_sum_man_vec_34;
  wire       [71:0]   tmp_sum_man_vec_35;
  wire       [71:0]   tmp_sum_man_vec_36;
  wire       [71:0]   tmp_sum_man_vec_37;
  wire       [71:0]   tmp_sum_man_vec_38;
  wire       [71:0]   tmp_sum_man_vec_39;
  wire       [71:0]   tmp_sum_man_vec_40;
  wire       [71:0]   tmp_sum_man_vec_41;
  wire       [71:0]   tmp_sum_man_vec_42;
  wire       [71:0]   tmp_sum_man_vec_43;
  wire       [71:0]   tmp_sum_man_vec_44;
  wire       [71:0]   tmp_sum_man_vec_45;
  wire       [71:0]   tmp_sum_man_vec_46;
  wire       [71:0]   tmp_sum_man_vec_47;
  wire       [71:0]   tmp_sum_man_vec_48;
  wire       [71:0]   tmp_sum_man_vec_49;
  wire       [71:0]   tmp_sum_man_vec_50;
  wire       [71:0]   tmp_sum_man_vec_51;
  wire       [71:0]   tmp_sum_man_vec_52;
  wire       [71:0]   tmp_sum_man_vec_53;
  wire       [71:0]   tmp_sum_man_vec_54;
  wire       [71:0]   tmp_sum_man_vec_55;
  wire       [71:0]   tmp_sum_man_vec_56;
  wire       [71:0]   tmp_sum_man_vec_57;
  wire       [71:0]   tmp_sum_man_vec_58;
  wire       [71:0]   tmp_sum_man_vec_59;
  wire       [71:0]   tmp_sum_man_vec_60;
  wire       [71:0]   tmp_sum_man_vec_61;
  wire       [71:0]   tmp_sum_man_vec_62;
  wire       [71:0]   tmp_sum_man_vec_63;
  wire       [71:0]   tmp_sum_man_vec_64;
  wire       [71:0]   tmp_sum_man_vec_65;
  wire       [71:0]   tmp_sum_man_vec_66;
  wire       [71:0]   tmp_sum_man_vec_67;
  wire       [71:0]   tmp_sum_man_vec_68;
  wire       [71:0]   tmp_sum_man_vec_69;
  wire       [71:0]   tmp_sum_man_vec_70;
  wire       [71:0]   tmp_sum_man_vec_71;
  wire                tmp_found_71;
  wire                tmp_found_72;
  wire                tmp_found_73;
  wire                tmp_found_74;
  wire       [6:0]    tmp_lzc;
  wire       [6:0]    tmp_lzc_1;
  wire       [6:0]    tmp_lzc_2;
  wire       [6:0]    tmp_lzc_3;
  wire       [6:0]    tmp_lzc_4;
  wire       [6:0]    tmp_lzc_5;
  wire       [6:0]    tmp_lzc_6;
  wire       [6:0]    tmp_lzc_7;
  wire       [6:0]    tmp_lzc_8;
  wire       [6:0]    tmp_lzc_9;
  wire       [6:0]    tmp_lzc_10;
  wire       [6:0]    tmp_lzc_11;
  wire       [6:0]    tmp_lzc_real;
  wire       [71:0]   tmp_norm_man;
  wire       [71:0]   tmp_norm_man_1;
  wire       [71:0]   tmp_norm_man_2;
  wire       [198:0]  tmp_norm_man_3;
  wire       [7:0]    tmp_result_exp;
  wire       [7:0]    tmp_result_exp_1;
  wire       [7:0]    tmp_result_exp_2;
  wire       [7:0]    tmp_result_exp_3;
  wire       [0:0]    tmp_result_exp_4;
  wire       [7:0]    tmp_result_exp_5;
  wire       [0:0]    tmp_result_exp_6;
  wire       [0:0]    tmp_round_up_1;
  wire       [22:0]   tmp_man_rounded;
  wire       [0:0]    tmp_man_rounded_1;
  wire       [7:0]    tmp_exp_final;
  wire       [0:0]    tmp_exp_final_1;
  wire       [31:0]   tmp_norm_num;
  wire       [31:0]   tmp_subnorm_num;
  wire       [31:0]   tmp_subnorm_num_1;
  wire                a_sign;
  wire                b_sign;
  wire                c_sign;
  wire       [7:0]    a_exp;
  wire       [7:0]    b_exp;
  wire       [7:0]    c_exp;
  wire       [22:0]   a_man;
  wire       [22:0]   b_man;
  wire       [22:0]   c_man;
  wire       [0:0]    a_hidden;
  wire       [0:0]    b_hidden;
  wire       [0:0]    c_hidden;
  wire       [23:0]   a_man_1;
  wire       [23:0]   b_man_1;
  wire       [23:0]   c_man_1;
  wire                product_sign;
  wire       [7:0]    exp_all_one;
  wire                a_is_inf;
  wire                b_is_inf;
  wire                c_is_inf;
  wire                a_is_nan;
  wire                b_is_nan;
  wire                c_is_nan;
  wire                output_nan;
  wire                a_b_inf;
  wire                a_zero;
  wire                b_zero;
  wire                inf_x_zero;
  wire                prod_is_inf;
  wire                inf_cancel;
  wire                output_nan_inf;
  wire                inf_sign;
  wire       [7:0]    product_exp;
  wire                exp_diff_dir;
  reg        [7:0]    exp_diff;
  reg        [23:0]   a_man_1_r1;
  reg        [23:0]   b_man_1_r1;
  reg        [23:0]   c_man_1_r1;
  reg                 exp_diff_dir_r1;
  reg        [7:0]    exp_diff_r1;
  reg        [7:0]    product_exp_r1;
  reg        [7:0]    c_exp_r1;
  reg                 product_sign_r1;
  reg                 c_sign_r1;
  reg                 output_nan_inf_r1;
  reg                 inf_sign_r1;
  reg                 a_b_inf_r1;
  reg                 c_is_inf_r1;
  wire       [71:0]   c_man_ext;
  wire       [71:0]   product_man;
  reg        [71:0]   product_shift;
  reg        [71:0]   c_man_shift;
  wire                when_fp_mac_l120;
  wire                when_fp_mac_l127;
  wire       [71:0]   c_man_align;
  wire       [7:0]    product_exp_shift;
  reg        [71:0]   c_man_align_r2;
  reg        [7:0]    product_exp_shift_r2;
  reg        [71:0]   product_man_align_r2;
  reg                 product_sign_r2;
  reg                 c_sign_r2;
  reg                 output_nan_inf_r2;
  reg                 inf_sign_r2;
  reg                 a_b_inf_r2;
  reg                 c_is_inf_r2;
  wire       [72:0]   prod_mag_s;
  wire       [72:0]   c_mag_s;
  wire       [72:0]   prod_val;
  wire       [72:0]   c_val;
  wire       [73:0]   sum_man;
  wire       [73:0]   sum_man_abs_all;
  reg        [73:0]   sum_man_abs_all_r3;
  reg        [7:0]    product_exp_shift_r3;
  reg                 output_nan_inf_r3;
  reg                 inf_sign_r3;
  reg                 a_b_inf_r3;
  reg                 c_is_inf_r3;
  reg                 sum_man_sign_r3;
  wire       [71:0]   sum_man_abs;
  wire                sum_man_overflow;
  wire                sum_man_vec_0;
  wire                sum_man_vec_1;
  wire                sum_man_vec_2;
  wire                sum_man_vec_3;
  wire                sum_man_vec_4;
  wire                sum_man_vec_5;
  wire                sum_man_vec_6;
  wire                sum_man_vec_7;
  wire                sum_man_vec_8;
  wire                sum_man_vec_9;
  wire                sum_man_vec_10;
  wire                sum_man_vec_11;
  wire                sum_man_vec_12;
  wire                sum_man_vec_13;
  wire                sum_man_vec_14;
  wire                sum_man_vec_15;
  wire                sum_man_vec_16;
  wire                sum_man_vec_17;
  wire                sum_man_vec_18;
  wire                sum_man_vec_19;
  wire                sum_man_vec_20;
  wire                sum_man_vec_21;
  wire                sum_man_vec_22;
  wire                sum_man_vec_23;
  wire                sum_man_vec_24;
  wire                sum_man_vec_25;
  wire                sum_man_vec_26;
  wire                sum_man_vec_27;
  wire                sum_man_vec_28;
  wire                sum_man_vec_29;
  wire                sum_man_vec_30;
  wire                sum_man_vec_31;
  wire                sum_man_vec_32;
  wire                sum_man_vec_33;
  wire                sum_man_vec_34;
  wire                sum_man_vec_35;
  wire                sum_man_vec_36;
  wire                sum_man_vec_37;
  wire                sum_man_vec_38;
  wire                sum_man_vec_39;
  wire                sum_man_vec_40;
  wire                sum_man_vec_41;
  wire                sum_man_vec_42;
  wire                sum_man_vec_43;
  wire                sum_man_vec_44;
  wire                sum_man_vec_45;
  wire                sum_man_vec_46;
  wire                sum_man_vec_47;
  wire                sum_man_vec_48;
  wire                sum_man_vec_49;
  wire                sum_man_vec_50;
  wire                sum_man_vec_51;
  wire                sum_man_vec_52;
  wire                sum_man_vec_53;
  wire                sum_man_vec_54;
  wire                sum_man_vec_55;
  wire                sum_man_vec_56;
  wire                sum_man_vec_57;
  wire                sum_man_vec_58;
  wire                sum_man_vec_59;
  wire                sum_man_vec_60;
  wire                sum_man_vec_61;
  wire                sum_man_vec_62;
  wire                sum_man_vec_63;
  wire                sum_man_vec_64;
  wire                sum_man_vec_65;
  wire                sum_man_vec_66;
  wire                sum_man_vec_67;
  wire                sum_man_vec_68;
  wire                sum_man_vec_69;
  wire                sum_man_vec_70;
  wire                sum_man_vec_71;
  wire                tmp_found;
  wire                tmp_found_1;
  wire                tmp_found_2;
  wire                tmp_found_3;
  wire                tmp_found_4;
  wire                tmp_found_5;
  wire                tmp_found_6;
  wire                tmp_found_7;
  wire                tmp_found_8;
  wire                tmp_found_9;
  wire                tmp_found_10;
  wire                tmp_found_11;
  wire                tmp_found_12;
  wire                tmp_found_13;
  wire                tmp_found_14;
  wire                tmp_found_15;
  wire                tmp_found_16;
  wire                tmp_found_17;
  wire                tmp_found_18;
  wire                tmp_found_19;
  wire                tmp_found_20;
  wire                tmp_found_21;
  wire                tmp_found_22;
  wire                tmp_found_23;
  wire                tmp_found_24;
  wire                tmp_found_25;
  wire                tmp_found_26;
  wire                tmp_found_27;
  wire                tmp_found_28;
  wire                tmp_found_29;
  wire                tmp_found_30;
  wire                tmp_found_31;
  wire                tmp_found_32;
  wire                tmp_found_33;
  wire                tmp_found_34;
  wire                tmp_found_35;
  wire                tmp_found_36;
  wire                tmp_found_37;
  wire                tmp_found_38;
  wire                tmp_found_39;
  wire                tmp_found_40;
  wire                tmp_found_41;
  wire                tmp_found_42;
  wire                tmp_found_43;
  wire                tmp_found_44;
  wire                tmp_found_45;
  wire                tmp_found_46;
  wire                tmp_found_47;
  wire                tmp_found_48;
  wire                tmp_found_49;
  wire                tmp_found_50;
  wire                tmp_found_51;
  wire                tmp_found_52;
  wire                tmp_found_53;
  wire                tmp_found_54;
  wire                tmp_found_55;
  wire                tmp_found_56;
  wire                tmp_found_57;
  wire                tmp_found_58;
  wire                tmp_found_59;
  wire                tmp_found_60;
  wire                tmp_found_61;
  wire                tmp_found_62;
  wire                tmp_found_63;
  wire                tmp_found_64;
  wire                tmp_found_65;
  wire                tmp_found_66;
  wire                tmp_found_67;
  wire                tmp_found_68;
  wire                tmp_found_69;
  wire                tmp_found_70;
  wire                found;
  wire       [6:0]    lzc;
  wire       [6:0]    lzc_real;
  wire                lzc_large_subnormal;
  wire                lzc_huge_zero;
  wire                lzc_normal;
  reg        [6:0]    lzc_real_r4;
  reg        [73:0]   sum_man_abs_all_r4;
  reg        [7:0]    product_exp_shift_r4;
  reg                 output_nan_inf_r4;
  reg                 inf_sign_r4;
  reg                 a_b_inf_r4;
  reg                 c_is_inf_r4;
  reg                 sum_man_sign_r4;
  reg                 lzc_large_subnormal_r4;
  reg                 lzc_huge_zero_r4;
  reg                 lzc_normal_r4;
  wire       [71:0]   sum_man_abs_r4;
  wire                sum_man_overflow_r4;
  wire       [71:0]   norm_man;
  wire       [7:0]    result_exp;
  wire       [23:0]   result_man;
  wire                guard_bit;
  wire                round_bit;
  wire                sticky_bit;
  reg                 tmp_round_up;
  wire                round_up;
  wire       [22:0]   man_rounded;
  wire                man_overflow;
  wire       [7:0]    exp_final;
  wire       [22:0]   man_final;
  wire       [31:0]   norm_num;
  wire                sub_sign;
  wire       [31:0]   subnorm_num;
  wire       [31:0]   z;
  reg        [22:0]   tmp_io_z;
  wire                when_fp_mac_l254;
  function [22:0] zz_tmp_io_z(input dummy);
    begin
      zz_tmp_io_z = 23'h000000;
      zz_tmp_io_z[22] = 1'b1;
    end
  endfunction
  wire [22:0] tmp_1;

  assign tmp_a_hidden = (a_exp != 8'h00);
  assign tmp_b_hidden = (b_exp != 8'h00);
  assign tmp_c_hidden = (c_exp != 8'h00);
  assign tmp_product_exp = (a_exp + b_exp);
  assign tmp_c_man_ext = ({24'd0,tmp_c_man_ext_1} <<< 5'd24);
  assign tmp_c_man_ext_1 = {48'd0, c_man_1_r1};
  assign tmp_product_man = ({24'd0,tmp_product_man_1} <<< 5'd24);
  assign tmp_product_man_2 = man_booth4_io_z;
  assign tmp_product_man_1 = {24'd0, tmp_product_man_2};
  assign tmp_c_man_shift = (c_man_ext >>> exp_diff_r1);
  assign tmp_product_shift = (product_man >>> exp_diff_r1);
  assign tmp_c_man_align = ({23'd0,c_man_shift} <<< 5'd23);
  assign tmp_prod_mag_s = {1'd0, product_man_align_r2};
  assign tmp_c_mag_s = {1'd0, c_man_align_r2};
  assign tmp_prod_val = (- prod_mag_s);
  assign tmp_c_val = (- c_mag_s);
  assign tmp_sum_man = {{1{prod_val[72]}}, prod_val};
  assign tmp_sum_man_1 = {{1{c_val[72]}}, c_val};
  assign tmp_sum_man_abs_all = (sum_man[73] ? tmp_sum_man_abs_all_1 : sum_man);
  assign tmp_sum_man_abs_all_1 = (~ sum_man);
  assign tmp_sum_man_abs_all_3 = sum_man[73];
  assign tmp_sum_man_abs_all_2 = {73'd0, tmp_sum_man_abs_all_3};
  assign tmp_sum_man_sign_r3 = 74'h0000000000000000000;
  assign tmp_sum_man_sign_r3_1 = 74'h0000000000000000000;
  assign tmp_sum_man_vec_0 = sum_man_abs;
  assign tmp_sum_man_vec_1 = sum_man_abs;
  assign tmp_sum_man_vec_2 = sum_man_abs;
  assign tmp_sum_man_vec_3 = sum_man_abs;
  assign tmp_sum_man_vec_4 = sum_man_abs;
  assign tmp_sum_man_vec_5 = sum_man_abs;
  assign tmp_sum_man_vec_6 = sum_man_abs;
  assign tmp_sum_man_vec_7 = sum_man_abs;
  assign tmp_sum_man_vec_8 = sum_man_abs;
  assign tmp_sum_man_vec_9 = sum_man_abs;
  assign tmp_sum_man_vec_10 = sum_man_abs;
  assign tmp_sum_man_vec_11 = sum_man_abs;
  assign tmp_sum_man_vec_12 = sum_man_abs;
  assign tmp_sum_man_vec_13 = sum_man_abs;
  assign tmp_sum_man_vec_14 = sum_man_abs;
  assign tmp_sum_man_vec_15 = sum_man_abs;
  assign tmp_sum_man_vec_16 = sum_man_abs;
  assign tmp_sum_man_vec_17 = sum_man_abs;
  assign tmp_sum_man_vec_18 = sum_man_abs;
  assign tmp_sum_man_vec_19 = sum_man_abs;
  assign tmp_sum_man_vec_20 = sum_man_abs;
  assign tmp_sum_man_vec_21 = sum_man_abs;
  assign tmp_sum_man_vec_22 = sum_man_abs;
  assign tmp_sum_man_vec_23 = sum_man_abs;
  assign tmp_sum_man_vec_24 = sum_man_abs;
  assign tmp_sum_man_vec_25 = sum_man_abs;
  assign tmp_sum_man_vec_26 = sum_man_abs;
  assign tmp_sum_man_vec_27 = sum_man_abs;
  assign tmp_sum_man_vec_28 = sum_man_abs;
  assign tmp_sum_man_vec_29 = sum_man_abs;
  assign tmp_sum_man_vec_30 = sum_man_abs;
  assign tmp_sum_man_vec_31 = sum_man_abs;
  assign tmp_sum_man_vec_32 = sum_man_abs;
  assign tmp_sum_man_vec_33 = sum_man_abs;
  assign tmp_sum_man_vec_34 = sum_man_abs;
  assign tmp_sum_man_vec_35 = sum_man_abs;
  assign tmp_sum_man_vec_36 = sum_man_abs;
  assign tmp_sum_man_vec_37 = sum_man_abs;
  assign tmp_sum_man_vec_38 = sum_man_abs;
  assign tmp_sum_man_vec_39 = sum_man_abs;
  assign tmp_sum_man_vec_40 = sum_man_abs;
  assign tmp_sum_man_vec_41 = sum_man_abs;
  assign tmp_sum_man_vec_42 = sum_man_abs;
  assign tmp_sum_man_vec_43 = sum_man_abs;
  assign tmp_sum_man_vec_44 = sum_man_abs;
  assign tmp_sum_man_vec_45 = sum_man_abs;
  assign tmp_sum_man_vec_46 = sum_man_abs;
  assign tmp_sum_man_vec_47 = sum_man_abs;
  assign tmp_sum_man_vec_48 = sum_man_abs;
  assign tmp_sum_man_vec_49 = sum_man_abs;
  assign tmp_sum_man_vec_50 = sum_man_abs;
  assign tmp_sum_man_vec_51 = sum_man_abs;
  assign tmp_sum_man_vec_52 = sum_man_abs;
  assign tmp_sum_man_vec_53 = sum_man_abs;
  assign tmp_sum_man_vec_54 = sum_man_abs;
  assign tmp_sum_man_vec_55 = sum_man_abs;
  assign tmp_sum_man_vec_56 = sum_man_abs;
  assign tmp_sum_man_vec_57 = sum_man_abs;
  assign tmp_sum_man_vec_58 = sum_man_abs;
  assign tmp_sum_man_vec_59 = sum_man_abs;
  assign tmp_sum_man_vec_60 = sum_man_abs;
  assign tmp_sum_man_vec_61 = sum_man_abs;
  assign tmp_sum_man_vec_62 = sum_man_abs;
  assign tmp_sum_man_vec_63 = sum_man_abs;
  assign tmp_sum_man_vec_64 = sum_man_abs;
  assign tmp_sum_man_vec_65 = sum_man_abs;
  assign tmp_sum_man_vec_66 = sum_man_abs;
  assign tmp_sum_man_vec_67 = sum_man_abs;
  assign tmp_sum_man_vec_68 = sum_man_abs;
  assign tmp_sum_man_vec_69 = sum_man_abs;
  assign tmp_sum_man_vec_70 = sum_man_abs;
  assign tmp_sum_man_vec_71 = sum_man_abs;
  assign tmp_lzc_real = lzc;
  assign tmp_norm_man_1 = (sum_man_abs_all_r4[72 : 0] >>> 1'd1);
  assign tmp_norm_man = tmp_norm_man_1;
  assign tmp_norm_man_3 = ({127'd0,sum_man_abs_r4} <<< lzc_real_r4);
  assign tmp_norm_man_2 = tmp_norm_man_3[71:0];
  assign tmp_result_exp = (tmp_result_exp_1 + tmp_result_exp_3);
  assign tmp_result_exp_1 = (product_exp_shift_r4 - tmp_result_exp_2);
  assign tmp_result_exp_2 = {1'd0, lzc_real_r4};
  assign tmp_result_exp_4 = norm_man[71];
  assign tmp_result_exp_3 = {7'd0, tmp_result_exp_4};
  assign tmp_result_exp_6 = sum_man_overflow_r4;
  assign tmp_result_exp_5 = {7'd0, tmp_result_exp_6};
  assign tmp_round_up_1 = tmp_round_up;
  assign tmp_man_rounded_1 = round_up;
  assign tmp_man_rounded = {22'd0, tmp_man_rounded_1};
  assign tmp_exp_final_1 = man_overflow;
  assign tmp_exp_final = {7'd0, tmp_exp_final_1};
  assign tmp_norm_num = {{sum_man_sign_r4,exp_final},man_final};
  assign tmp_subnorm_num_1 = {{sub_sign,8'h00},man_final};
  assign tmp_subnorm_num = tmp_subnorm_num_1;
  assign tmp_found_71 = ((((((((((((((((tmp_found_72 || tmp_found_41) || tmp_found_42) || tmp_found_43) || tmp_found_44) || tmp_found_45) || tmp_found_46) || tmp_found_47) || tmp_found_48) || tmp_found_49) || tmp_found_50) || tmp_found_51) || tmp_found_52) || tmp_found_53) || tmp_found_54) || tmp_found_55) || tmp_found_56);
  assign tmp_found_72 = ((((((((((((((((tmp_found_73 || tmp_found_25) || tmp_found_26) || tmp_found_27) || tmp_found_28) || tmp_found_29) || tmp_found_30) || tmp_found_31) || tmp_found_32) || tmp_found_33) || tmp_found_34) || tmp_found_35) || tmp_found_36) || tmp_found_37) || tmp_found_38) || tmp_found_39) || tmp_found_40);
  assign tmp_found_73 = ((((((((((((((((tmp_found_74 || tmp_found_9) || tmp_found_10) || tmp_found_11) || tmp_found_12) || tmp_found_13) || tmp_found_14) || tmp_found_15) || tmp_found_16) || tmp_found_17) || tmp_found_18) || tmp_found_19) || tmp_found_20) || tmp_found_21) || tmp_found_22) || tmp_found_23) || tmp_found_24);
  assign tmp_found_74 = ((((((((tmp_found || tmp_found_1) || tmp_found_2) || tmp_found_3) || tmp_found_4) || tmp_found_5) || tmp_found_6) || tmp_found_7) || tmp_found_8);
  assign tmp_lzc = 7'h0a;
  assign tmp_lzc_1 = (tmp_found_11 ? 7'h0b : (tmp_found_12 ? 7'h0c : (tmp_found_13 ? 7'h0d : (tmp_found_14 ? 7'h0e : (tmp_found_15 ? 7'h0f : (tmp_found_16 ? 7'h10 : (tmp_found_17 ? 7'h11 : (tmp_found_18 ? 7'h12 : (tmp_found_19 ? 7'h13 : (tmp_found_20 ? 7'h14 : (tmp_found_21 ? tmp_lzc_2 : tmp_lzc_3)))))))))));
  assign tmp_lzc_2 = 7'h15;
  assign tmp_lzc_3 = (tmp_found_22 ? 7'h16 : (tmp_found_23 ? 7'h17 : (tmp_found_24 ? 7'h18 : (tmp_found_25 ? 7'h19 : (tmp_found_26 ? 7'h1a : (tmp_found_27 ? 7'h1b : (tmp_found_28 ? 7'h1c : (tmp_found_29 ? 7'h1d : (tmp_found_30 ? 7'h1e : (tmp_found_31 ? 7'h1f : (tmp_found_32 ? tmp_lzc_4 : tmp_lzc_5)))))))))));
  assign tmp_lzc_4 = 7'h20;
  assign tmp_lzc_5 = (tmp_found_33 ? 7'h21 : (tmp_found_34 ? 7'h22 : (tmp_found_35 ? 7'h23 : (tmp_found_36 ? 7'h24 : (tmp_found_37 ? 7'h25 : (tmp_found_38 ? 7'h26 : (tmp_found_39 ? 7'h27 : (tmp_found_40 ? 7'h28 : (tmp_found_41 ? 7'h29 : (tmp_found_42 ? 7'h2a : (tmp_found_43 ? tmp_lzc_6 : tmp_lzc_7)))))))))));
  assign tmp_lzc_6 = 7'h2b;
  assign tmp_lzc_7 = (tmp_found_44 ? 7'h2c : (tmp_found_45 ? 7'h2d : (tmp_found_46 ? 7'h2e : (tmp_found_47 ? 7'h2f : (tmp_found_48 ? 7'h30 : (tmp_found_49 ? 7'h31 : (tmp_found_50 ? 7'h32 : (tmp_found_51 ? 7'h33 : (tmp_found_52 ? 7'h34 : (tmp_found_53 ? 7'h35 : (tmp_found_54 ? tmp_lzc_8 : tmp_lzc_9)))))))))));
  assign tmp_lzc_8 = 7'h36;
  assign tmp_lzc_9 = (tmp_found_55 ? 7'h37 : (tmp_found_56 ? 7'h38 : (tmp_found_57 ? 7'h39 : (tmp_found_58 ? 7'h3a : (tmp_found_59 ? 7'h3b : (tmp_found_60 ? 7'h3c : (tmp_found_61 ? 7'h3d : (tmp_found_62 ? 7'h3e : (tmp_found_63 ? 7'h3f : (tmp_found_64 ? 7'h40 : (tmp_found_65 ? tmp_lzc_10 : tmp_lzc_11)))))))))));
  assign tmp_lzc_10 = 7'h41;
  assign tmp_lzc_11 = (tmp_found_66 ? 7'h42 : (tmp_found_67 ? 7'h43 : (tmp_found_68 ? 7'h44 : (tmp_found_69 ? 7'h45 : (tmp_found_70 ? 7'h46 : 7'h47)))));
  mult_booth4 man_booth4 (
    .io_a  (man_booth4_io_a[23:0]), //i
    .io_b  (man_booth4_io_b[23:0]), //i
    .io_tc (1'b0                 ), //i
    .io_z  (man_booth4_io_z[47:0])  //o
  );
  assign a_sign = io_a[31];
  assign b_sign = io_b[31];
  assign c_sign = io_c[31];
  assign a_exp = io_a[30 : 23];
  assign b_exp = io_b[30 : 23];
  assign c_exp = io_c[30 : 23];
  assign a_man = io_a[22 : 0];
  assign b_man = io_b[22 : 0];
  assign c_man = io_c[22 : 0];
  assign a_hidden = tmp_a_hidden;
  assign b_hidden = tmp_b_hidden;
  assign c_hidden = tmp_c_hidden;
  assign a_man_1 = {a_hidden,a_man};
  assign b_man_1 = {b_hidden,b_man};
  assign c_man_1 = {c_hidden,c_man};
  assign product_sign = (a_sign ^ b_sign);
  assign exp_all_one = 8'hff;
  assign a_is_inf = ((a_exp == exp_all_one) && (a_man == 23'h000000));
  assign b_is_inf = ((b_exp == exp_all_one) && (b_man == 23'h000000));
  assign c_is_inf = ((c_exp == exp_all_one) && (c_man == 23'h000000));
  assign a_is_nan = ((a_exp == exp_all_one) && (a_man != 23'h000000));
  assign b_is_nan = ((b_exp == exp_all_one) && (b_man != 23'h000000));
  assign c_is_nan = ((c_exp == exp_all_one) && (c_man != 23'h000000));
  assign output_nan = ((a_is_nan || b_is_nan) || c_is_nan);
  assign a_b_inf = (a_is_inf || b_is_inf);
  assign a_zero = ((a_exp == 8'h00) && (a_man == 23'h000000));
  assign b_zero = ((b_exp == 8'h00) && (b_man == 23'h000000));
  assign inf_x_zero = ((a_is_inf && b_zero) || (b_is_inf && a_zero));
  assign prod_is_inf = (a_b_inf && (! inf_x_zero));
  assign inf_cancel = ((prod_is_inf && c_is_inf) && (product_sign != c_sign));
  assign output_nan_inf = ((output_nan || inf_x_zero) || inf_cancel);
  assign inf_sign = (a_b_inf ? product_sign : c_sign);
  assign product_exp = (tmp_product_exp - 8'h7f);
  assign exp_diff_dir = (c_exp < product_exp);
  always @(*) begin
    if(exp_diff_dir) begin
      exp_diff = (product_exp - c_exp);
    end else begin
      exp_diff = (c_exp - product_exp);
    end
  end

  assign man_booth4_io_a = a_man_1_r1;
  assign man_booth4_io_b = b_man_1_r1;
  assign c_man_ext = tmp_c_man_ext[71:0];
  assign product_man = tmp_product_man[71:0];
  always @(*) begin
    if(exp_diff_dir_r1) begin
      product_shift = product_man;
    end else begin
      if(when_fp_mac_l127) begin
        product_shift = tmp_product_shift;
      end else begin
        product_shift = 72'h000000000000000000;
      end
    end
  end

  assign when_fp_mac_l120 = (exp_diff_r1 < 8'h30);
  always @(*) begin
    if(exp_diff_dir_r1) begin
      if(when_fp_mac_l120) begin
        c_man_shift = tmp_c_man_shift;
      end else begin
        c_man_shift = 72'h000000000000000000;
      end
    end else begin
      c_man_shift = c_man_ext;
    end
  end

  assign when_fp_mac_l127 = (exp_diff_r1 < 8'h30);
  assign c_man_align = tmp_c_man_align[71:0];
  assign product_exp_shift = (exp_diff_dir_r1 ? product_exp_r1 : c_exp_r1);
  assign prod_mag_s = tmp_prod_mag_s;
  assign c_mag_s = tmp_c_mag_s;
  assign prod_val = (product_sign_r2 ? tmp_prod_val : prod_mag_s);
  assign c_val = (c_sign_r2 ? tmp_c_val : c_mag_s);
  assign sum_man = ($signed(tmp_sum_man) + $signed(tmp_sum_man_1));
  assign sum_man_abs_all = (tmp_sum_man_abs_all + tmp_sum_man_abs_all_2);
  assign sum_man_abs = sum_man_abs_all_r3[71 : 0];
  assign sum_man_overflow = sum_man_abs_all_r3[72];
  assign sum_man_vec_0 = tmp_sum_man_vec_0[71];
  assign sum_man_vec_1 = tmp_sum_man_vec_1[70];
  assign sum_man_vec_2 = tmp_sum_man_vec_2[69];
  assign sum_man_vec_3 = tmp_sum_man_vec_3[68];
  assign sum_man_vec_4 = tmp_sum_man_vec_4[67];
  assign sum_man_vec_5 = tmp_sum_man_vec_5[66];
  assign sum_man_vec_6 = tmp_sum_man_vec_6[65];
  assign sum_man_vec_7 = tmp_sum_man_vec_7[64];
  assign sum_man_vec_8 = tmp_sum_man_vec_8[63];
  assign sum_man_vec_9 = tmp_sum_man_vec_9[62];
  assign sum_man_vec_10 = tmp_sum_man_vec_10[61];
  assign sum_man_vec_11 = tmp_sum_man_vec_11[60];
  assign sum_man_vec_12 = tmp_sum_man_vec_12[59];
  assign sum_man_vec_13 = tmp_sum_man_vec_13[58];
  assign sum_man_vec_14 = tmp_sum_man_vec_14[57];
  assign sum_man_vec_15 = tmp_sum_man_vec_15[56];
  assign sum_man_vec_16 = tmp_sum_man_vec_16[55];
  assign sum_man_vec_17 = tmp_sum_man_vec_17[54];
  assign sum_man_vec_18 = tmp_sum_man_vec_18[53];
  assign sum_man_vec_19 = tmp_sum_man_vec_19[52];
  assign sum_man_vec_20 = tmp_sum_man_vec_20[51];
  assign sum_man_vec_21 = tmp_sum_man_vec_21[50];
  assign sum_man_vec_22 = tmp_sum_man_vec_22[49];
  assign sum_man_vec_23 = tmp_sum_man_vec_23[48];
  assign sum_man_vec_24 = tmp_sum_man_vec_24[47];
  assign sum_man_vec_25 = tmp_sum_man_vec_25[46];
  assign sum_man_vec_26 = tmp_sum_man_vec_26[45];
  assign sum_man_vec_27 = tmp_sum_man_vec_27[44];
  assign sum_man_vec_28 = tmp_sum_man_vec_28[43];
  assign sum_man_vec_29 = tmp_sum_man_vec_29[42];
  assign sum_man_vec_30 = tmp_sum_man_vec_30[41];
  assign sum_man_vec_31 = tmp_sum_man_vec_31[40];
  assign sum_man_vec_32 = tmp_sum_man_vec_32[39];
  assign sum_man_vec_33 = tmp_sum_man_vec_33[38];
  assign sum_man_vec_34 = tmp_sum_man_vec_34[37];
  assign sum_man_vec_35 = tmp_sum_man_vec_35[36];
  assign sum_man_vec_36 = tmp_sum_man_vec_36[35];
  assign sum_man_vec_37 = tmp_sum_man_vec_37[34];
  assign sum_man_vec_38 = tmp_sum_man_vec_38[33];
  assign sum_man_vec_39 = tmp_sum_man_vec_39[32];
  assign sum_man_vec_40 = tmp_sum_man_vec_40[31];
  assign sum_man_vec_41 = tmp_sum_man_vec_41[30];
  assign sum_man_vec_42 = tmp_sum_man_vec_42[29];
  assign sum_man_vec_43 = tmp_sum_man_vec_43[28];
  assign sum_man_vec_44 = tmp_sum_man_vec_44[27];
  assign sum_man_vec_45 = tmp_sum_man_vec_45[26];
  assign sum_man_vec_46 = tmp_sum_man_vec_46[25];
  assign sum_man_vec_47 = tmp_sum_man_vec_47[24];
  assign sum_man_vec_48 = tmp_sum_man_vec_48[23];
  assign sum_man_vec_49 = tmp_sum_man_vec_49[22];
  assign sum_man_vec_50 = tmp_sum_man_vec_50[21];
  assign sum_man_vec_51 = tmp_sum_man_vec_51[20];
  assign sum_man_vec_52 = tmp_sum_man_vec_52[19];
  assign sum_man_vec_53 = tmp_sum_man_vec_53[18];
  assign sum_man_vec_54 = tmp_sum_man_vec_54[17];
  assign sum_man_vec_55 = tmp_sum_man_vec_55[16];
  assign sum_man_vec_56 = tmp_sum_man_vec_56[15];
  assign sum_man_vec_57 = tmp_sum_man_vec_57[14];
  assign sum_man_vec_58 = tmp_sum_man_vec_58[13];
  assign sum_man_vec_59 = tmp_sum_man_vec_59[12];
  assign sum_man_vec_60 = tmp_sum_man_vec_60[11];
  assign sum_man_vec_61 = tmp_sum_man_vec_61[10];
  assign sum_man_vec_62 = tmp_sum_man_vec_62[9];
  assign sum_man_vec_63 = tmp_sum_man_vec_63[8];
  assign sum_man_vec_64 = tmp_sum_man_vec_64[7];
  assign sum_man_vec_65 = tmp_sum_man_vec_65[6];
  assign sum_man_vec_66 = tmp_sum_man_vec_66[5];
  assign sum_man_vec_67 = tmp_sum_man_vec_67[4];
  assign sum_man_vec_68 = tmp_sum_man_vec_68[3];
  assign sum_man_vec_69 = tmp_sum_man_vec_69[2];
  assign sum_man_vec_70 = tmp_sum_man_vec_70[1];
  assign sum_man_vec_71 = tmp_sum_man_vec_71[0];
  assign tmp_found = (sum_man_vec_0 == 1'b1);
  assign tmp_found_1 = (sum_man_vec_1 == 1'b1);
  assign tmp_found_2 = (sum_man_vec_2 == 1'b1);
  assign tmp_found_3 = (sum_man_vec_3 == 1'b1);
  assign tmp_found_4 = (sum_man_vec_4 == 1'b1);
  assign tmp_found_5 = (sum_man_vec_5 == 1'b1);
  assign tmp_found_6 = (sum_man_vec_6 == 1'b1);
  assign tmp_found_7 = (sum_man_vec_7 == 1'b1);
  assign tmp_found_8 = (sum_man_vec_8 == 1'b1);
  assign tmp_found_9 = (sum_man_vec_9 == 1'b1);
  assign tmp_found_10 = (sum_man_vec_10 == 1'b1);
  assign tmp_found_11 = (sum_man_vec_11 == 1'b1);
  assign tmp_found_12 = (sum_man_vec_12 == 1'b1);
  assign tmp_found_13 = (sum_man_vec_13 == 1'b1);
  assign tmp_found_14 = (sum_man_vec_14 == 1'b1);
  assign tmp_found_15 = (sum_man_vec_15 == 1'b1);
  assign tmp_found_16 = (sum_man_vec_16 == 1'b1);
  assign tmp_found_17 = (sum_man_vec_17 == 1'b1);
  assign tmp_found_18 = (sum_man_vec_18 == 1'b1);
  assign tmp_found_19 = (sum_man_vec_19 == 1'b1);
  assign tmp_found_20 = (sum_man_vec_20 == 1'b1);
  assign tmp_found_21 = (sum_man_vec_21 == 1'b1);
  assign tmp_found_22 = (sum_man_vec_22 == 1'b1);
  assign tmp_found_23 = (sum_man_vec_23 == 1'b1);
  assign tmp_found_24 = (sum_man_vec_24 == 1'b1);
  assign tmp_found_25 = (sum_man_vec_25 == 1'b1);
  assign tmp_found_26 = (sum_man_vec_26 == 1'b1);
  assign tmp_found_27 = (sum_man_vec_27 == 1'b1);
  assign tmp_found_28 = (sum_man_vec_28 == 1'b1);
  assign tmp_found_29 = (sum_man_vec_29 == 1'b1);
  assign tmp_found_30 = (sum_man_vec_30 == 1'b1);
  assign tmp_found_31 = (sum_man_vec_31 == 1'b1);
  assign tmp_found_32 = (sum_man_vec_32 == 1'b1);
  assign tmp_found_33 = (sum_man_vec_33 == 1'b1);
  assign tmp_found_34 = (sum_man_vec_34 == 1'b1);
  assign tmp_found_35 = (sum_man_vec_35 == 1'b1);
  assign tmp_found_36 = (sum_man_vec_36 == 1'b1);
  assign tmp_found_37 = (sum_man_vec_37 == 1'b1);
  assign tmp_found_38 = (sum_man_vec_38 == 1'b1);
  assign tmp_found_39 = (sum_man_vec_39 == 1'b1);
  assign tmp_found_40 = (sum_man_vec_40 == 1'b1);
  assign tmp_found_41 = (sum_man_vec_41 == 1'b1);
  assign tmp_found_42 = (sum_man_vec_42 == 1'b1);
  assign tmp_found_43 = (sum_man_vec_43 == 1'b1);
  assign tmp_found_44 = (sum_man_vec_44 == 1'b1);
  assign tmp_found_45 = (sum_man_vec_45 == 1'b1);
  assign tmp_found_46 = (sum_man_vec_46 == 1'b1);
  assign tmp_found_47 = (sum_man_vec_47 == 1'b1);
  assign tmp_found_48 = (sum_man_vec_48 == 1'b1);
  assign tmp_found_49 = (sum_man_vec_49 == 1'b1);
  assign tmp_found_50 = (sum_man_vec_50 == 1'b1);
  assign tmp_found_51 = (sum_man_vec_51 == 1'b1);
  assign tmp_found_52 = (sum_man_vec_52 == 1'b1);
  assign tmp_found_53 = (sum_man_vec_53 == 1'b1);
  assign tmp_found_54 = (sum_man_vec_54 == 1'b1);
  assign tmp_found_55 = (sum_man_vec_55 == 1'b1);
  assign tmp_found_56 = (sum_man_vec_56 == 1'b1);
  assign tmp_found_57 = (sum_man_vec_57 == 1'b1);
  assign tmp_found_58 = (sum_man_vec_58 == 1'b1);
  assign tmp_found_59 = (sum_man_vec_59 == 1'b1);
  assign tmp_found_60 = (sum_man_vec_60 == 1'b1);
  assign tmp_found_61 = (sum_man_vec_61 == 1'b1);
  assign tmp_found_62 = (sum_man_vec_62 == 1'b1);
  assign tmp_found_63 = (sum_man_vec_63 == 1'b1);
  assign tmp_found_64 = (sum_man_vec_64 == 1'b1);
  assign tmp_found_65 = (sum_man_vec_65 == 1'b1);
  assign tmp_found_66 = (sum_man_vec_66 == 1'b1);
  assign tmp_found_67 = (sum_man_vec_67 == 1'b1);
  assign tmp_found_68 = (sum_man_vec_68 == 1'b1);
  assign tmp_found_69 = (sum_man_vec_69 == 1'b1);
  assign tmp_found_70 = (sum_man_vec_70 == 1'b1);
  assign found = (((((((((((((((tmp_found_71 || tmp_found_57) || tmp_found_58) || tmp_found_59) || tmp_found_60) || tmp_found_61) || tmp_found_62) || tmp_found_63) || tmp_found_64) || tmp_found_65) || tmp_found_66) || tmp_found_67) || tmp_found_68) || tmp_found_69) || tmp_found_70) || (sum_man_vec_71 == 1'b1));
  assign lzc = (tmp_found ? 7'h00 : (tmp_found_1 ? 7'h01 : (tmp_found_2 ? 7'h02 : (tmp_found_3 ? 7'h03 : (tmp_found_4 ? 7'h04 : (tmp_found_5 ? 7'h05 : (tmp_found_6 ? 7'h06 : (tmp_found_7 ? 7'h07 : (tmp_found_8 ? 7'h08 : (tmp_found_9 ? 7'h09 : (tmp_found_10 ? tmp_lzc : tmp_lzc_1)))))))))));
  assign lzc_real = (sum_man_overflow ? 7'h00 : ((! found) ? 7'h48 : tmp_lzc_real));
  assign lzc_large_subnormal = ((7'h30 <= lzc_real) && (lzc_real < 7'h48));
  assign lzc_huge_zero = (7'h48 <= lzc_real);
  assign lzc_normal = (lzc_real < 7'h30);
  assign sum_man_abs_r4 = sum_man_abs_all_r4[71 : 0];
  assign sum_man_overflow_r4 = sum_man_abs_all_r4[72];
  assign norm_man = (sum_man_overflow_r4 ? tmp_norm_man : tmp_norm_man_2);
  assign result_exp = (tmp_result_exp + tmp_result_exp_5);
  assign result_man = norm_man[71 : 48];
  assign guard_bit = norm_man[47];
  assign round_bit = norm_man[46];
  assign sticky_bit = (|norm_man[45 : 24]);
  always @(*) begin
    case(io_rnd)
      3'b000 : begin
        tmp_round_up = (guard_bit && ((round_bit || sticky_bit) || result_man[0]));
      end
      3'b001 : begin
        tmp_round_up = 1'b0;
      end
      3'b010 : begin
        tmp_round_up = (sum_man_sign_r4 && ((guard_bit || round_bit) || sticky_bit));
      end
      3'b011 : begin
        tmp_round_up = ((! sum_man_sign_r4) && ((guard_bit || round_bit) || sticky_bit));
      end
      3'b100 : begin
        tmp_round_up = (guard_bit && (round_bit || sticky_bit));
      end
      default : begin
        tmp_round_up = (guard_bit && ((round_bit || sticky_bit) || result_man[0]));
      end
    endcase
  end

  assign round_up = tmp_round_up_1[0];
  assign man_rounded = (result_man[22 : 0] + tmp_man_rounded);
  assign man_overflow = ((&result_man[22 : 0]) && round_up);
  assign exp_final = (result_exp[7 : 0] + tmp_exp_final);
  assign man_final = ((&exp_final) ? 23'h000000 : man_rounded);
  assign norm_num = tmp_norm_num;
  assign sub_sign = (sum_man_sign_r4 && (|man_final));
  assign subnorm_num = (lzc_huge_zero_r4 ? 32'h00000000 : tmp_subnorm_num);
  assign z = (lzc_normal_r4 ? norm_num : subnorm_num);
  assign tmp_1 = zz_tmp_io_z(1'b0);
  always @(*) tmp_io_z = tmp_1;
  assign when_fp_mac_l254 = (a_b_inf_r4 || c_is_inf_r4);
  always @(posedge clk) begin
    a_man_1_r1 <= a_man_1;
    b_man_1_r1 <= b_man_1;
    c_man_1_r1 <= c_man_1;
    exp_diff_dir_r1 <= exp_diff_dir;
    exp_diff_r1 <= exp_diff;
    product_exp_r1 <= product_exp;
    c_exp_r1 <= c_exp;
    product_sign_r1 <= product_sign;
    c_sign_r1 <= c_sign;
    output_nan_inf_r1 <= output_nan_inf;
    inf_sign_r1 <= inf_sign;
    a_b_inf_r1 <= a_b_inf;
    c_is_inf_r1 <= c_is_inf;
    c_man_align_r2 <= c_man_align;
    product_exp_shift_r2 <= product_exp_shift;
    product_man_align_r2 <= product_shift;
    product_sign_r2 <= product_sign_r1;
    c_sign_r2 <= c_sign_r1;
    output_nan_inf_r2 <= output_nan_inf_r1;
    inf_sign_r2 <= inf_sign_r1;
    a_b_inf_r2 <= a_b_inf_r1;
    c_is_inf_r2 <= c_is_inf_r1;
    sum_man_abs_all_r3 <= sum_man_abs_all;
    product_exp_shift_r3 <= product_exp_shift_r2;
    output_nan_inf_r3 <= output_nan_inf_r2;
    inf_sign_r3 <= inf_sign_r2;
    a_b_inf_r3 <= a_b_inf_r2;
    c_is_inf_r3 <= c_is_inf_r2;
    sum_man_sign_r3 <= (($signed(sum_man) < $signed(tmp_sum_man_sign_r3)) && (! ($signed(sum_man) == $signed(tmp_sum_man_sign_r3_1))));
    lzc_real_r4 <= lzc_real;
    sum_man_abs_all_r4 <= sum_man_abs_all_r3;
    product_exp_shift_r4 <= product_exp_shift_r3;
    output_nan_inf_r4 <= output_nan_inf_r3;
    inf_sign_r4 <= inf_sign_r3;
    a_b_inf_r4 <= a_b_inf_r3;
    c_is_inf_r4 <= c_is_inf_r3;
    sum_man_sign_r4 <= sum_man_sign_r3;
    lzc_large_subnormal_r4 <= lzc_large_subnormal;
    lzc_huge_zero_r4 <= lzc_huge_zero;
    lzc_normal_r4 <= lzc_normal;
  end

  always @(posedge clk or negedge resetn) begin
    if(!resetn) begin
      io_z <= 32'h00000000;
      io_status <= 8'h00;
    end else begin
      if(output_nan_inf_r4) begin
        io_z <= {{1'b0,8'hff},tmp_io_z};
        io_status <= 8'h01;
      end else begin
        if(when_fp_mac_l254) begin
          io_z <= {{inf_sign_r4,8'hff},23'h000000};
          io_status <= 8'h02;
        end else begin
          io_z <= z;
          io_status <= 8'h00;
        end
      end
    end
  end


endmodule
